#!/bin/bash
pm2 stop gosspravki
git pull /home/git/gosspravki.git master
rm -f -r /home/gosspravki/react_egrn/build
rm -f -r /home/gosspravki/egrn_nodejs/public/build
cd /home/gosspravki/react_egrn/
npm run build
mv /home/gosspravki/react_egrn/build/ /home/gosspravki/egrn_nodejs/public/build 
pm2 start gosspravki